apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80       # External port (accessible outside the cluster)
      targetPort: 80 # Matches the containerPort in the Deployment
  type: LoadBalancer  # Exposes Nginx externally (use "ClusterIP" for internal-only)
